### ISSUE TITLE
Comparison to dj-paddle

### ISSUE THREAD

**Issue by DeeeeLAN** [kennell/django-paddle#4]
In your opinion, how does the state of this project compare to the seemingly-abandoned dj-paddle project? I am getting geared up to switch from stripe to paddle and I want to make sure I am using a package that is worth investing time and resources into. I will plan on filing pull requests for any issues I run into as much as it makes sense to do, so I want to spend time on the right project.

**Comment by kennell** [comment]
This project, as is, is used in production by some sites and works fine for them.  However, it has limited functionality. It currently only handles subscriptions, payments and plans. More important, just like the abandoned `dj-paddle`, it uses the legacy ["Classic" API](https://developer.paddle.com/classic) rather than the new ["Billing" API](https://developer.paddle.com/). I have not checked how similar these APIs are and i currently have no plans of testing this package with the new API.

To my understanding the Classic API is no longer available to new Paddle accounts; so i would not recommend using this package for new projects.

**Comment by DeeeeLAN** [comment]
Thanks. I found the active [django-paddle-billing](https://github.com/websideproject/django-paddle-billing) project which supports the new billing API.
